Небольшое улучшение системы действий
Lost-Paradise-Project/Lost-Paradise pull request #149
Opened 2024-09-16 12:30 UTC by DarkSide-droids

# VIVA LA LOST PARADISE!
![image](https://i.imgur.com/hLEDvQY.png)

## Описание обновления:
- Я решил добавить несколько новых дейтвий в меню взаимодействия, а также добавить прикольные иконки показывающие  те или иные состояния. Также, к некоторым действиям добавились и звуки

**Медиа**
![изображение](https://github.com/user-attachments/assets/d60f1124-36fe-4301-a394-cf43533d3e49)
![изображение](https://github.com/user-attachments/assets/3785005c-098b-417f-86d7-0c683756ca5f)

**Проверки**

- [x] PR завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
- [x] Я не добавлял контент нарушающий чужие авторские права.

**Изменения**

:cl: MrDarkSide
- add: Добавлены новые действия в панель взаимодействия
- add: Список новых действий: Шлёпнуть, пощёчина, лизнуть, похлопать по плечу, поцеловать, показать средний палец, поцелуй, поцелуй в щеку, диагностика состояния системы (КПБ-борги).

- add: Также, были добавлены новые эффекты настроения: Легкое смущение, облегчение(При нанесении пощечины), обида (При получении пощечины), Ободрение, Любовь (При поцелуях и так далее)

- tweak: Изменены некоторые проблемы с переводом, иконками, действиями в панели взаимодействий
- fix: Исправлены пару ошибок перевода панели взаимодействия.

2024-09-16 19:52 UTC, KashRas2 requested changes

2024-09-16 19:52 UTC, KashRas2 commented on Resources/Prototypes/_LostParadise/Interactions/Popups/interaction_popups.yml
> +  popupType: MediumErotic
Нет такого типа popup'а.

2024-09-16 19:52 UTC, KashRas2 commented on Resources/Prototypes/_LostParadise/Interactions/Popups/interaction_popups.yml
> +  id: MediumErotic
LPP перед айди.

2024-09-16 19:52 UTC, KashRas2 commented on Resources/Prototypes/_LostParadise/Interactions/interactions.yml
> +# - type: Interaction
Не рекомендуется оставлять подобные строчки комментариев с кодом. Либо доделать, либо убрать.

2024-09-16 19:54 UTC, KashRas2 commented on Resources/Prototypes/_LostParadise/Interactions/Popups/interaction_popups.yml
> +  popupType: MediumErotic
https://github.com/Lost-Paradise-Project/Lost-Paradise/blob/b7af1fca743274a75f1c35f760a60796b80874cf/Resources/Prototypes/Interactions/Popups/interaction_popups.yml#L3

Для примера

2024-09-17 11:09 UTC, DarkSide-droids commented
Все ошибки исправил, спасибо за помощь @KashRas2

2024-09-17 16:27 UTC, merged