Vector+МикроСБ апдейт
Lost-Paradise-Project/Lost-Paradise pull request #213
Opened 2024-09-26 21:08 UTC by MegaDaimond

# VIVA LA LOST PARADISE!
![image](https://i.imgur.com/hLEDvQY.png)

## Описание обновления:
Изменил Вектор, плюсом слегка поменял СБ

**Проверки**

- [x] PR завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
- [x] Я не добавлял контент нарушающий чужие авторские права.
- [x] Я добавил свой контент только в папку _LostParadise(только если вы не меняете оригинальный код).
- [x] Я не добавлял переводы в прототипы, а сделал их в файле locale.

**Изменения**

:cl: MegaDaimond
- add: Добавлены новые виды .10 патронов (Резиновые, тренировочные, урановые, бронебойные)
- add: Добавлены коробки под .10 патроны
- tweak: Вектор теперь использует .10 патроны, а не .45 магнум
- tweak: Магазин под вектора теперь вмещает 40 патронов .10
- tweak: Цена на вектор в планшете уменьшилась 11>5 ЦентКоинов
- tweak: Планшет закупа СБ перемещён из кармана смотрителя в его шкафчик
- tweak: С небольшим шансом станнеры могут появится в шкафчиках СБ
- tweak: ГП и КМ получили миниатюрные лазерные пистолеты в их шкафчики

2024-09-26 21:51 UTC, Evgencheg requested changes
перевести всё что осталось, перенести новый код в наши папки.

2024-09-28 22:05 UTC, Evgencheg commented
@coderabbitai full review

2024-09-28 22:16 UTC, Evgencheg commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/rifle.yml
> +
@coderabbitai В прототипе любого предмета после поля component: должно идти -type на уровне с буквой с в component

2024-09-28 22:18 UTC, Evgencheg commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: LPPHOSUplinkShop #На будущее, будет хайриском
@coderabbitai при удалении дополнительного дополнения по типу prob: можно оставить оригинальную часть с - id:

2024-09-28 22:28 UTC, Evgencheg commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
> +    proto: LPPCartridgeMinigunrubber
@coderabbitai совет, пиши скрипты для .sh и для .bat чтобы пользователи windows могли использовать их.

2024-09-28 22:32 UTC, Flybik commented
Пиздец бот насрал

2024-09-28 22:35 UTC, Evgencheg commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - LPPMagazineBoxMinigunRubber
@coderabbitai совет, используй https://github.com/Lost-Paradise-Project/Lost-Paradise/blob/master/Content.YAMLLinter/Content.YAMLLinter.csproj для правильной работы проверок yaml файлов

2024-09-28 22:48 UTC, Evgencheg commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - LPPMagazineBoxMinigunRubber
> @Evgencheg, спасибо за совет. Чтобы обеспечить правильную проверку YAML-файлов, я могу учитывать правила из `Content.YAMLLinter.csproj`. Пожалуйста, добавьте соответствующие настройки линтера в конфигурацию проекта, чтобы я мог их использовать при проверке.
> 
> (_/) (•.•) (>🐰<)

Как это сделать?

2024-09-29 14:44 UTC, Evgencheg commented
@coderabbitai review

2024-09-29 15:38 UTC, Evgencheg commented on Resources/Prototypes/_LostParadise/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/LPPCartridge.yml
> +
@coderabbitai весь текст в yaml/yml должен быть на английском

2024-09-29 16:18 UTC, merged