Чуть-чуть баланса ловких рук и медленный едок
Lost-Paradise-Project/Lost-Paradise pull request #321
Opened 2024-11-05 09:20 UTC by IAmLePacko

## Описание обновления:
В общем, да, всё как в названии.

**Проверки**

- [ ] PR завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
- [ ] Я не добавлял контент нарушающий чужие авторские права.
- [ ] Я добавил свой контент только в папку _LostParadise(только если вы не меняете оригинальный код).
- [ ] Я не добавлял переводы в прототипы, а сделал их с помощью скрипта translations.bat в Tools/SS14_RU.

:cl: IAmLePacko
- add: Добавлен перк "Медленный едок"

2024-11-05 10:03 UTC, IAmLePacko commented
Надеюсь, всё нормально

2024-11-05 13:04 UTC, IAmLePacko commented
@coderabbitai

2024-11-05 13:08 UTC, IAmLePacko commented
Дурак, не удалял я изоляцию, что ты тут рассказываешь

2024-11-05 21:06 UTC, Evgencheg commented
@IAmLePacko наши шняги во первых, называются по id LPPTrait/LPPItem и ЛОКАЛИЗАЦИЯ должна быть в нашей папке, с английской версией в том числе

2024-11-05 21:06 UTC, Evgencheg requested changes
Сменить айди и вставить всё в наши папки.

2024-11-06 04:26 UTC, closed without merging

2024-11-06 04:27 UTC, IAmLePacko commented
Проще новый

2024-11-06 04:27 UTC, Flybik approved these changes
Заебися

2024-11-06 04:28 UTC, Flybik commented
> Проще новый

Нет, открываешь бранч, меняешь, коммитишь, ничего сложного

2024-11-06 04:44 UTC, IAmLePacko commented
> > Проще новый
> 
> Нет, открываешь бранч, меняешь, коммитишь, ничего сложного

Поздно