Add double mattress
Lost-Paradise-Project/Lost-Paradise pull request #339
Opened 2024-12-12 20:53 UTC by FuchsiaThePhoenix

![image](https://i.imgur.com/hLEDvQY.png)

## Описание обновления:

**Медиа**

![Снимок экрана 2024-12-12 223956](https://github.com/user-attachments/assets/cf2d6384-11d3-439c-8fdf-f15cc041b5bb)
![Снимок экрана 2024-12-12 223948](https://github.com/user-attachments/assets/7c402e4a-6e03-4164-8e21-42c8b868625d)

**Проверки**

- [x] PR завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
- [x] Я не добавлял контент нарушающий чужие авторские права.
- [x] Я добавил свой контент только в папку _LostParadise(только если вы не меняете оригинальный код).
- [x] Я не добавлял переводы в прототипы, а сделал их с помощью скрипта translations.bat в Tools/SS14_RU.

**Изменения**

:cl: FuchsiaThePhoenix
- add: Добавлены двойные матрасы

2024-12-16 14:46 UTC, Evgencheg requested changes
Пофиксить ошибки)

2024-12-16 15:01 UTC, FuchsiaThePhoenix commented
> Пофиксить ошибки)

![Screenshot_20241216_175736.jpg](https://github.com/user-attachments/assets/54b554e4-c63e-4ae3-8507-56cc017f3544)

![Screenshot_20241216_175652.jpg](https://github.com/user-attachments/assets/be8243bc-add8-4541-bd7f-554a773ee057)

![Screenshot_20241216_175533.jpg](https://github.com/user-attachments/assets/df66699a-d7e4-4089-8dd0-d36e3a953ab2)

Из этих ошибок идут только жалобы на YAML, бот жалуется на graph: LPPMattressDouble

2024-12-23 16:06 UTC, Evgencheg requested changes
Переводы сделаны не через скрипт. Ай ай ай...

2024-12-31 08:28 UTC, FuchsiaThePhoenix commented
> Переводы сделаны не через скрипт. Ай ай ай...

У меня скрипт не работает

2025-01-27 12:57 UTC, Evgencheg commented
Работа не выполняется. Пулл реквест не обновляется.

2025-01-27 12:57 UTC, closed without merging