Печати уровней доступа и должностей
Lost-Paradise-Project/Lost-Paradise pull request #343
Opened 2024-12-18 18:12 UTC by CovidDoctor

![image](https://i.imgur.com/hLEDvQY.png)

## Описание обновления:
Ввёл немножечко печатей. Адъютант и Офицер "Синий Щит" получили собственные печати, а также было добавлено больше разнообразия в печати Центрального Командования и печати уровней доступа.

**Проверки**
- [x] PR завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
- [ ] Я не добавлял контент нарушающий чужие авторские права. 
(Возможно забыл изменить лицензию в мете по пути Resources\Textures\_LostParadise\Objects\Misc\stamps.rsi)
- [ ] Я добавил свой контент только в папку _LostParadise(только если вы не меняете оригинальный код).
- [ ] Я не добавлял переводы в прототипы, а сделал их с помощью скрипта translations.bat в Tools/SS14_RU.

**Изменения**
- add: Добавлены печати Адъютанта и Офицера "Синий Щит"
- add: Добавлены печати 4 уровней доступа: Служебного пользования, Ограниченного пользования, Секретно и Совершенно секретно.
- add: Добавлен ряд печатей для игроков Белого Списка(ЦК)

2024-12-21 13:52 UTC, Flybik commented
```Resources/Textures/Clothing/Head/Hardsuits/deathsquad.rsi: PNG not defined in metadata: on-inhand-right.png
Resources/Textures/Clothing/Head/Hardsuits/capspace.rsi: PNG not defined in metadata: inhand-left.png
Resources/Textures/Clothing/Head/Hardsuits/capspace.rsi: PNG not defined in metadata: equipped-HELMET-tajaran.png
Resources/Textures/Clothing/Mask/gassecurity.rsi: PNG not defined in metadata: up-equipped-MASK-vox.png
Resources/Textures/Clothing/Mask/medical.rsi: PNG not defined in metadata: equipped-MASK-vox.png```

2024-12-22 15:37 UTC, Evgencheg requested changes
Не использовался скрипт для переводов ent-. Ужэс...
Читай требования и гайды в закрепах дискорда

2024-12-24 16:19 UTC, Evgencheg approved these changes
Сюдааааааааааааааааааааа

2024-12-27 17:23 UTC, BL02DL approved these changes

2025-01-10 13:04 UTC, closed without merging